function data() {
	// exposed module
}
module.exports = data;

data.random_bind = {
	"string": "strList",
	"date": "source_date2015-01-01*2016-04-01*YYYY-MM-DD",
	"boolean": "source_boolean",
	"number": "random10Digits",
	"id": "source_uuid",
  "Name-lastName": "lastNameList",
  "Name-firstName": "firstNameList",
  "User-primaryEmail": "emailList",
  "User-addr": "addrLineOneList",
  "User-city": "cityList",
  "User-state": "stateList",
  "Random_number": "random10Digits",
  "Random_UUID": "source_uuid",
  "Account-policyNumber": "randomIntWith14digits",
  "Claim-ClaimAmount": "randomDoubleWith10digitsDollar",
  "Account-purchasedDate": "source_date2015-01-01*2016-04-01*YYYY-MM-DD",
  "Account-lastStatusChangeDate": "source_date01/04/2016*06/30/2016*MM/DD/YYYY",
  "Account-expirationDate": "source_boolean"
};

data.random_source = {
  "lastNameList": [
    "Raymond",
    "Ruiz",
    "Cole",
    "Harvey",
    "Melton",
    "Greene",
    "Hill",
    "Richardson",
    "Hudson",
    "Boone",
    "Shepard",
    "Carson",
    "Duke",
    "Mills",
    "Kemp",
    "Shepherd"
  ],
  "firstNameList": [
    "Jescie",
    "Cullen",
    "Renee",
    "Neville",
    "Yvonne",
    "Carlos",
    "Kiayada",
    "Russell",
    "Amelia",
    "Anthony",
    "Tatiana",
    "Tate",
    "Kyla",
    "Lawrence",
    "Ocean"
  ],
  "emailList": [
    "nec.ligula@nislarcu.org",
    "natoque.penatibus@fringilla.ca",
    "ornare.lectus@posuere.ca",
    "cubilia.Curae.Phasellus@interdum.com",
    "egestas.urna@eget.edu",
    "Cras@ametfaucibusut.edu",
    "volutpat@nisisem.co.uk",
    "at@nonjustoProin.net",
    "ullamcorper.velit.in@luctusvulputatenisi.net",
    "rutrum.non.hendrerit@ligulaAeneangravida.org",
    "Sed@lorem.ca",
    "vehicula.aliquet.libero@ut.edu",
    "Aenean.massa@vehiculaaliquet.co.uk",
    "laoreet.ipsum.Curabitur@interdumfeugiatSed.edu",
    "senectus.et.netus@velitAliquam.edu",
    "Aliquam.nisl.Nulla@ametrisus.com",
    "aliquet@enim.org",
    "Mauris@Aliquamrutrumlorem.com",
    "erat.Sed@Nunc.org",
    "enim@nuncnulla.ca",
    "diam@non.co.uk",
    "et@Phasellusin.ca",
    "senectus@etultricesposuere.org",
    "tempus.mauris@Innec.net",
    "non.dui.nec@vehicula.ca",
    "velit.Aliquam.nisl@Duis.ca",
    "a@Aliquam.co.uk"
  ],
  "addrLineOneList": [
    "9617 Egestas Ave",
    "P.O. Box 502, 8087 Sit Street",
    "854-1929 Integer St.",
    "5412 Rutrum Ave",
    "P.O. Box 904, 238 Nec Ave",
    "699-1774 Dictum Avenue",
    "Ap #995-4633 Nam St.",
    "2895 Feugiat Rd.",
    "Ap #454-4967 Egestas Rd.",
    "Ap #702-7211 A, St.",
    "8068 Non, St.",
    "1429 Ornare, Ave",
    "Ap #632-4823 Vitae Street",
    "P.O. Box 231, 9147 Auctor, Av.",
    "Ap #767-3229 Consequat, Ave",
    "P.O. Box 507, 955 Malesuada Av.",
    "289-1997 Sem St.",
    "3443 Vestibulum St.",
    "Ap #676-435 Molestie Avenue",
    "714-1556 Ut Rd.",
    "297-1329 Class Avenue",
    "P.O. Box 151, 7986 Nibh. Rd.",
    "407-4437 Vitae Rd.",
    "P.O. Box 462, 8211 Leo Av.",
    "Ap #810-6065 Nec Ave",
    "P.O. Box 897, 4315 Ut, Rd.",
    "222-7374 Mattis. Avenue",
    "820-7021 Cursus. St.",
    "Ap #194-5346 Nibh Rd.",
    "P.O. Box 547, 5006 Consectetuer Ave",
    "7638 Tristique St.",
    "565-6377 Quis Av.",
    "2682 Donec Street",
    "5628 In St.",
    "Ap #544-6487 Lectus Avenue",
    "P.O. Box 358, 286 Mattis Rd.",
    "3866 Tempor Avenue",
    "120-2318 Amet, Rd.",
    "Ap #980-8121 Dui Ave",
    "P.O. Box 739, 1813 In, Street",
    "Ap #232-1467 Imperdiet Street"
  ],
  "cityList": [
    "Chelsea",
    "Homburg",
    "San Marcello",
    "Portofino",
    "Helmond",
    "Linz",
    "Aalbeke",
    "Ehein",
    "Burntisland",
    "Sint-Pauwels",
    "Kallo",
    "Cimitile",
    "Stony Plain",
    "Neu-Isenburg",
    "Mission",
    "Halle",
    "Wimmertingen",
    "Savannah",
    "Osimo",
    "Merchtem",
    "Guadalajara",
    "Kettering",
    "Herne",
    "Malartic",
    "La Hulpe",
    "Tilburg",
    "Caplan",
    "Houston",
    "Castelmarte",
    "Wetteren",
    "Cincinnati",
    "Adrano",
    "Antwerpen",
    "Rodgau",
    "Helensburgh",
    "Elversele",
    "Glauchau",
    "Limal",
    "Capannori",
    "Vichte",
    "Sambreville",
    "Husum",
    "Banff",
    "Rueglio",
    "Juneau",
    "Sydney",
    "Asso",
    "Emmen",
    "Montleban",
    "Banchory",
    "Castellafiume",
    "Treglio",
    "Wodonga",
    "Senftenberg",
    "Rotem",
    "Bloomington",
    "Baden",
    "Legal",
    "Pukekohe",
    "Springdale",
    "Gosnells",
    "Guelph",
    "Deventer",
    "Latinne",
    "Wechelderzande",
    "Trieste",
    "Cumbernauld",
    "Altavilla Irpina",
    "Grande Prairie",
    "Duns",
    "Fernie",
    "Kaiserslauter",
    "Castelluccio Superiore",
    "Dubuisson",
    "Erli",
    "Newark",
    "Thame",
    "Viernheim",
    "Isca sullo Ionio",
    "Hudson Bay",
    "Bromyard",
    "Memphis"
  ],
  "stateList": [
    "AL",
    "AK",
    "AS",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "GU",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MH",
    "MA",
    "MI",
    "FM",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "MP",
    "OH",
    "OK",
    "OR",
    "PW",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "VI",
    "WA",
    "WV",
    "WI",
    "WY"
  ],
  "strList": [
    "conclusionemque",
    "concludaturque",
    "delicatissimi",
    "deterruisset",
    "interpretaris",
    "mediocritatem",
    "signiferumque",
    "complectitur",
    "consectetuer",
    "contentiones",
    "definitiones",
    "deterruisset",
    "eloquentiam",
    "liberavisse",
    "reprehendunt",
    "repudiandae",
    "accommodare",
    "adversarium",
    "dissentiet",
    "dissentiunt",
    "eloquentiam",
    "expetendis",
    "instructior",
    "intellegam",
    "posidonium",
    "referrentur",
    "reprimique",
    "scriptorem",
    "ullamcorper",
    "abhorreant",
    "accusamus",
    "aliquando",
    "assueverit",
    "constituto",
    "definiebas",
    "democritum",
    "efficiendi",
    "elaboraret",
    "expetendis",
    "explicari",
    "inciderint",
    "interesset",
    "maiestatis",
    "molestiae",
    "omittantur",
    "pertinacia",
    "postulant",
    "scribentur",
    "temporibus",
    "vituperata"
  ],
  "randomIntWith14digits": "function() {return Math.floor(Math.random() * 90000000000000) + 10000000000000}",
  "randomDoubleWith10digitsDollar": "function() {return '$' + ((Math.random() * 9000000) + 1000000).toFixed(2)}",
  "random10Digits": "function() {return Math.floor(Math.random() * 9000000000) + 1000000000}"
};